class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'RoadSoS',
      'tagline': 'Golden Hour · One-tap emergency',
      'tap_for_emergency': 'Tap for Emergency',
      'emergency_services': 'Emergency Services',
      'first_aid_guides': 'First Aid Guides',
      'breakdown_assistance': 'Breakdown Assistance',
      'emergency_contacts': 'Emergency Contacts',
      'offline_emergency_hub': 'Open Offline Emergency Hub',
      'offline_hub_desc': 'Access offline helplines & location data',
      'analytics_dashboard': 'Incident Analytics',
      'volunteer_directory': 'Volunteer Responders',
      'emergency_profile': 'Emergency Profile',
      'language_settings': 'Language Settings',
      'crash_detection': 'Crash Detection',
      'sos_active': 'SOS ACTIVE',
      'location_shown_below': 'Your location is shown below',
      'broadcast_sos_alert': 'BROADCAST SOS ALERT',
      'possible_crash_detected': 'POSSIBLE CRASH DETECTED',
      'are_you_safe': 'Are you safe?',
      'im_safe': "I'M SAFE",
      'need_help': 'NEED HELP',
      'auto_sos_timer_desc': 'Sending emergency SOS automatically',
      'gathering_gps_alert': 'Gathering GPS & Alerting Contacts.',
      'low_risk': 'Low Risk',
      'medium_risk': 'Medium Risk',
      'high_risk': 'High Risk',
      'golden_hour_assessment': 'Golden Hour Risk Assessment',
      'hospital_dist': 'Distance to nearest hospital',
      'police_dist': 'Distance to nearest police station',
      'network_availability': 'Network availability',
      'low_risk_desc': 'Emergency services are very close and network is stable. Stay calm. Help should arrive shortly.',
      'medium_risk_desc': 'Some services are slightly delayed. If you are mobile, consider moving closer to the main road.',
      'high_risk_desc': 'Critical alert. Nearest medical assistance is far and network is limited. Seek local assistance or safe transport immediately.',
      'blood_group': 'Blood Group',
      'allergies': 'Allergies / Drug Sensitivities',
      'medical_conditions': 'Medical Conditions',
      'emergency_notes': 'Emergency Instructions / Notes',
      'primary_contact_name': 'Primary Contact Name',
      'primary_contact_phone': 'Primary Contact Phone Number',
      'save_profile': 'SAVE PROFILE DETAILS',
      'profile_saved_success': 'Emergency profile updated successfully!',
    },
    'te': {
      'app_title': 'రోడ్‌SOS',
      'tagline': 'గోల్డన్ అవర్ · ఒక్క నొక్కుతో అత్యవసర సహాయం',
      'tap_for_emergency': 'అత్యవసరానికి నొక్కండి',
      'emergency_services': 'అత్యవసర సేవలు',
      'first_aid_guides': 'ప్రథమ చికిత్స మార్గదర్శకాలు',
      'breakdown_assistance': 'బ్రేక్‌డౌన్ సహాయం',
      'emergency_contacts': 'అత్యవసర పరిచయాలు',
      'offline_emergency_hub': 'ఆఫ్‌లైన్ అత్యవసర హబ్ తెరువు',
      'offline_hub_desc': 'ఆఫ్‌లైన్ హెల్ప్‌లైన్లు & లొకేషన్ డేటా యాక్సెస్ చేయి',
      'analytics_dashboard': 'సంఘటన విశ్లేషణలు',
      'volunteer_directory': 'వాలంటీర్ రెస్పాండర్లు',
      'emergency_profile': 'అత్యవసర ప్రొఫైల్',
      'language_settings': 'భాష సెట్టింగులు',
      'crash_detection': 'క్రాష్ డిటెక్షన్',
      'sos_active': 'SOS యాక్టివ్',
      'location_shown_below': 'మీ లొకేషన్ దిగువన చూపబడింది',
      'broadcast_sos_alert': 'SOS అలర్ట్ ప్రసారం చేయి',
      'possible_crash_detected': 'క్రాష్ అయినట్లు గుర్తించబడింది',
      'are_you_safe': 'మీరు సురక్షితంగా ఉన్నారా?',
      'im_safe': 'నేను సురక్షితంగా ఉన్నాను',
      'need_help': 'సహాయం కావాలి',
      'auto_sos_timer_desc': 'అత్యవసర SOS స్వయంచాలకంగా పంపబడుతోంది',
      'gathering_gps_alert': 'GPS సేకరిస్తోంది & పరిచయాలకు అలర్ట్ చేస్తోంది.',
      'low_risk': 'తక్కువ ప్రమాదం',
      'medium_risk': 'మధ్యస్థ ప్రమాదం',
      'high_risk': 'అధిక ప్రమాదం',
      'golden_hour_assessment': 'గోల్డన్ అవర్ రిస్క్ అసెస్‌మెంట్',
      'hospital_dist': 'సమీప ఆసుపత్రికి దూరం',
      'police_dist': 'సమీప పోలీస్ స్టేషన్‌కు దూరం',
      'network_availability': 'నెట్‌వర్క్ లభ్యత',
      'low_risk_desc': 'అత్యవసర సేవలు చాలా దగ్గర్లో ఉన్నాయి మరియు నెట్‌వర్క్ స్థిరంగా ఉంది. శాంతంగా ఉండండి. సహాయం త్వరలో వస్తుంది.',
      'medium_risk_desc': 'కొన్ని సేవలు కొంచెం ఆలస్యమవుతున్నాయి. మీరు కదలగలిగితే, ప్రధాన రోడ్డుకు దగ్గరగా వెళ్ళడాన్ని పరిగణించండి.',
      'high_risk_desc': 'క్రిటికల్ అలర్ట్. సమీప వైద్య సహాయం దూరంగా ఉంది మరియు నెట్‌వర్క్ పరిమితంగా ఉంది. స్థానిక స్వయంసేవకుల సహాయం కోరండి లేదా వెంటనే సురక్షిత రవాణాను ప్రయత్నించండి.',
      'blood_group': 'రక్త వర్గం',
      'allergies': 'అలర్జీలు / మందుల సున్నితత్వం',
      'medical_conditions': 'వైద్య పరిస్థితులు',
      'emergency_notes': 'అత్యవసర సూచనలు / నోట్స్',
      'primary_contact_name': 'ప్రాథమిక పరిచయం పేరు',
      'primary_contact_phone': 'ప్రాథమిక పరిచయం ఫోన్ నంబర్',
      'save_profile': 'ప్రొఫైల్ వివరాలు సేవ్ చేయి',
      'profile_saved_success': 'అత్యవసర ప్రొఫైల్ విజయవంతంగా నవీకరించబడింది!',
    },
    'hi': {
      'app_title': 'रोडSOS',
      'tagline': 'गोल्डन आवर · एक टैप आपातकालीन सहायता',
      'tap_for_emergency': 'आपातकाल के लिए टैप करें',
      'emergency_services': 'आपातकालीन सेवाएं',
      'first_aid_guides': 'प्राथमिक चिकित्सा गाइड',
      'breakdown_assistance': 'ब्रेकडाउन सहायता',
      'emergency_contacts': 'आपातकालीन संपर्क',
      'offline_emergency_hub': 'ऑफलाइन आपातकालीन हब खोलें',
      'offline_hub_desc': 'ऑफलाइन हेल्पलाइन और लोकेशन डेटा एक्सेस करें',
      'analytics_dashboard': 'घटना विश्लेषण',
      'volunteer_directory': 'स्वयंसेवी उत्तरदाता',
      'emergency_profile': 'आपातकालीन प्रोफ़ाइल',
      'language_settings': 'भाषा सेटिंग्स',
      'crash_detection': 'क्रैश डिटेक्शन',
      'sos_active': 'SOS सक्रिय',
      'location_shown_below': 'आपकी लोकेशन नीचे दिखाई गई है',
      'broadcast_sos_alert': 'SOS अलर्ट प्रसारित करें',
      'possible_crash_detected': 'संभावित दुर्घटना का पता चला',
      'are_you_safe': 'क्या आप सुरक्षित हैं?',
      'im_safe': 'मैं सुरक्षित हूं',
      'need_help': 'मदद चाहिए',
      'auto_sos_timer_desc': 'आपातकालीन SOS स्वचालित रूप से भेजा जा रहा है',
      'gathering_gps_alert': 'GPS एकत्र किया जा रहा है और संपर्कों को सतर्क किया जा रहा है।',
      'low_risk': 'कम जोखिम',
      'medium_risk': 'मध्यम जोखिम',
      'high_risk': 'उच्च जोखिम',
      'golden_hour_assessment': 'गोल्डन आवर जोखिम मूल्यांकन',
      'hospital_dist': 'निकटतम अस्पताल की दूरी',
      'police_dist': 'निकटतम पुलिस स्टेशन की दूरी',
      'network_availability': 'नेटवर्क उपलब्धता',
      'low_risk_desc': 'आपातकालीन सेवाएं बहुत करीब हैं और नेटवर्क स्थिर है। शांत रहें। सहायता शीघ्र ही पहुंच जाएगी।',
      'medium_risk_desc': 'कुछ सेवाओं में थोड़ी देरी हो सकती है। यदि आप सक्षम हैं, तो मुख्य सड़क के करीब जाने पर विचार करें।',
      'high_risk_desc': 'गंभीर चेतावनी। निकटतम चिकित्सा सहायता दूर है और नेटवर्क सीमित है। स्थानीय स्वयंसेवकों से सहायता लें या तुरंत सुरक्षित परिवहन की व्यवस्था करें।',
      'blood_group': 'रक्त समूह',
      'allergies': 'एलर्जी / दवा संवेदनशीलता',
      'medical_conditions': 'चिकित्सा स्थितियां',
      'emergency_notes': 'आपातकालीन निर्देश / नोट्स',
      'primary_contact_name': 'प्राथमिक संपर्क का नाम',
      'primary_contact_phone': 'प्राथमिक संपर्क फ़ोन नंबर',
      'save_profile': 'प्रोफ़ाइल विवरण सहेजें',
      'profile_saved_success': 'आपातकालीन प्रोफ़ाइल सफलतापूर्वक अपडेट की गई!',
    },
    'ta': {
      'app_title': 'ரோட்SOS',
      'tagline': 'கோல்டன் அவர் · ஒரு தட்டல் அவசரகால உதவி',
      'tap_for_emergency': 'அவசரநிலைக்கு தட்டவும்',
      'emergency_services': 'அவசர சேவைகள்',
      'first_aid_guides': 'முதலுதவி வழிகாட்டிகள்',
      'breakdown_assistance': 'பழுது சீர்திருத்த உதவி',
      'emergency_contacts': 'அவசரகால தொடர்புகள்',
      'offline_emergency_hub': 'ஆஃப்லைன் அவசரகால மையம் திறக்கவும்',
      'offline_hub_desc': 'ஆஃப்லைன் உதவி எண்கள் & இருப்பிட தரவு அணுகவும்',
      'analytics_dashboard': 'சம்பவ பகுப்பாய்வு',
      'volunteer_directory': 'தன்னார்வ உதவியாளர்கள்',
      'emergency_profile': 'அவசரகால சுயவிவரம்',
      'language_settings': 'மொழி அமைப்புகள்',
      'crash_detection': 'விபத்து கண்டறிதல்',
      'sos_active': 'SOS செயல்பாட்டில் உள்ளது',
      'location_shown_below': 'உங்கள் இருப்பிடம் கீழே காட்டப்படுகிறது',
      'broadcast_sos_alert': 'SOS எச்சரிக்கை அனுப்பவும்',
      'possible_crash_detected': 'விபத்து நிகழ்ந்திருக்கலாம் என கண்டறியப்பட்டது',
      'are_you_safe': 'நீங்கள் பாதுகாப்பாக இருக்கிறீர்களா?',
      'im_safe': 'நான் பாதுகாப்பாக இருக்கிறேன்',
      'need_help': 'உதவி தேவை',
      'auto_sos_timer_desc': 'அவசர SOS தானாகவே அனுப்பப்படுகிறது',
      'gathering_gps_alert': 'GPS சேகரிக்கப்படுகிறது & தொடர்புகளுக்கு எச்சரிக்கை அனுப்பப்படுகிறது.',
      'low_risk': 'குறைந்த ஆபத்து',
      'medium_risk': 'நடுத்தர ஆபத்து',
      'high_risk': 'அதிக ஆபத்து',
      'golden_hour_assessment': 'பொன்னான நேர ஆபத்து மதிப்பீடு',
      'hospital_dist': 'அருகிலுள்ள மருத்துவமனைக்கான தூரம்',
      'police_dist': 'அருகிலுள்ள காவல் நிலையத்திற்கான தூரம்',
      'network_availability': 'நெட்வொர்க் இணைப்பு',
      'low_risk_desc': 'அவசர சேவைகள் மிக அருகில் உள்ளன மற்றும் நெட்வொர்க் சீராக உள்ளது. அமைதியாக இருக்கவும். உதவி விரைவில் வரும்.',
      'medium_risk_desc': 'சில சேவைகள் சற்று தாமதமாகலாம். உங்களால் முடிந்தால், பிரதான சாலைக்கு அருகில் செல்லவும்.',
      'high_risk_desc': 'முக்கிய எச்சரிக்கை. அருகிலுள்ள மருத்துவ உதவி தூரத்தில் உள்ளது மற்றும் நெட்வொர்க் குறைவாக உள்ளது. உள்ளூர் தன்னார்வலர்களிடம் உதவி கேட்கவும் அல்லது உடனே பாதுகாப்பான போக்குவரத்தை நாடவும்.',
      'blood_group': 'இரத்த வகை',
      'allergies': 'ஒவ்வாமை / மருந்து உணர்திறன்',
      'medical_conditions': 'மருத்துவ நிலைமைகள்',
      'emergency_notes': 'அவசரகால வழிமுறைகள் / குறிப்புகள்',
      'primary_contact_name': 'முதன்மை தொடர்பு நபர் பெயர்',
      'primary_contact_phone': 'முதன்மை தொடர்பு தொலைபேசி எண்',
      'save_profile': 'சுயவிவர விவரங்களை சேமி',
      'profile_saved_success': 'அவசரகால சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
    },
  };

  static String translate(String lang, String key) {
    final values = _localizedValues[lang] ?? _localizedValues['en']!;
    return values[key] ?? key;
  }
}
